CREATE TABLE IF NOT EXISTS BOOKS(
    BOOK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_NAME VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT
);
CREATE TABLE IF NOT EXISTS AUTHORS(
    AUTHOR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS GENRES(
    GENRE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    GENRE_NAME VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS COMMENTS(
    COMMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(255),
    TEXT VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS BOOK_COMMENTS(
    BOOK_ID BIGINT,
    COMMENT_ID BIGINT
);
ALTER TABLE BOOKS
    ADD FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHORS(AUTHOR_ID)
            ON DELETE SET NULL
                ON UPDATE SET NULL;
ALTER TABLE BOOKS
    ADD FOREIGN KEY (GENRE_ID)
        REFERENCES GENRES(GENRE_ID)
            ON DELETE SET NULL
                ON UPDATE SET NULL;
ALTER TABLE BOOK_COMMENTS
    ADD FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS(BOOK_ID)
            ON DELETE CASCADE
                ON UPDATE CASCADE;
ALTER TABLE BOOK_COMMENTS
    ADD FOREIGN KEY (COMMENT_ID)
        REFERENCES COMMENTS(COMMENT_ID)
            ON DELETE SET NULL
                ON UPDATE SET NULL;