version: '3.7'

networks:
  lan_microservices:

services:

  server:
    build:
      context: ./server
    restart: always
    ports:
      - 9080:9080
    volumes:
      - /opt/server/logs:/opt/server/logs
    networks:
      - lan_microservices

  client:
    build:
      context: ./client
    restart: always
    environment:
      EUREKA_URI: http://server:9080
    ports:
      - 9080:9080
    volumes:
      - /opt/client/logs:/opt/client/logs
    networks:
      - lan_microservices